const employee = [
  {
    id: 1,
    name: "Rohit Sharma",
    email: "emp1@example.com",
    password: "123",
    taskCount: { active: 1, completed: 1, failed: 0, newTask: 1 },
    tasks: [
      {
        taskId: 101,
        title: "Create Login UI",
        description: "Design and implement login screen",
        startDate: "2025-01-01",
        dueDate: "2025-01-05",
        group: "Frontend",
        percentCompleted: 100,
        status: "started",
        division: "UI",
        createdBy: "Admin",
        priority: "High",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskId: 102,
        title: "Fix Navbar Bug",
        description: "Resolve alignment issue in navbar",
        startDate: "2025-01-06",
        dueDate: "2025-01-08",
        group: "Frontend",
        percentCompleted: 60,
        status: "started",
        division: "UI",
        createdBy: "Admin",
        priority: "Medium",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskId: 103,
        title: "Write Unit Tests",
        description: "Add unit tests for components",
        startDate: "2025-01-09",
        dueDate: "2025-01-12",
        group: "Testing",
        percentCompleted: 0,
        status: "not started",
        division: "QA",
        createdBy: "Lead",
        priority: "Low",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },

  {
    id: 2,
    name: "Ananya Verma",
    email: "emp2@example.com",
    password: "123",
    taskCount: { active: 2, completed: 1, failed: 0, newTask: 0 },
    tasks: [
      {
        taskId: 201,
        title: "API Integration",
        description: "Integrate employee API",
        startDate: "2025-01-02",
        dueDate: "2025-01-07",
        group: "Backend",
        percentCompleted: 80,
        status: "started",
        division: "API",
        createdBy: "Admin",
        priority: "High",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskId: 202,
        title: "Error Handling",
        description: "Handle API error responses",
        startDate: "2025-01-08",
        dueDate: "2025-01-10",
        group: "Backend",
        percentCompleted: 100,
        status: "started",
        division: "API",
        createdBy: "Lead",
        priority: "Medium",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskId: 203,
        title: "Database Cleanup",
        description: "Remove unused records",
        startDate: "2025-01-11",
        dueDate: "2025-01-14",
        group: "Database",
        percentCompleted: 20,
        status: "started",
        division: "DB",
        createdBy: "Admin",
        priority: "Low",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },

  {
    id: 3,
    name: "Karthik Reddy",
    email: "emp3@example.com",
    password: "123",
    taskCount: { active: 1, completed: 1, failed: 0, newTask: 1 },
    tasks: [
      {
        taskId: 301,
        title: "Design Dashboard",
        description: "Create dashboard wireframes",
        startDate: "2025-01-03",
        dueDate: "2025-01-06",
        group: "Design",
        percentCompleted: 100,
        status: "started",
        division: "UX",
        createdBy: "Admin",
        priority: "High",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskId: 302,
        title: "User Research",
        description: "Conduct user interviews",
        startDate: "2025-01-07",
        dueDate: "2025-01-09",
        group: "Design",
        percentCompleted: 50,
        status: "started",
        division: "UX",
        createdBy: "Lead",
        priority: "Medium",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskId: 303,
        title: "Prepare Report",
        description: "UX findings report",
        startDate: "2025-01-10",
        dueDate: "2025-01-12",
        group: "Design",
        percentCompleted: 0,
        status: "not started",
        division: "UX",
        createdBy: "Admin",
        priority: "Low",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },

  {
    id: 4,
    name: "Sneha Patel",
    email: "emp4@example.com",
    password: "123",
    taskCount: { active: 1, completed: 1, failed: 0, newTask: 1 },
    tasks: [
      {
        taskId: 401,
        title: "UI Review",
        description: "Review UI components",
        startDate: "2025-01-04",
        dueDate: "2025-01-07",
        group: "Frontend",
        percentCompleted: 100,
        status: "started",
        division: "UI",
        createdBy: "Lead",
        priority: "Medium",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskId: 402,
        title: "Accessibility Fixes",
        description: "Fix accessibility issues",
        startDate: "2025-01-08",
        dueDate: "2025-01-11",
        group: "Frontend",
        percentCompleted: 40,
        status: "started",
        division: "UI",
        createdBy: "Admin",
        priority: "High",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskId: 403,
        title: "Style Guide",
        description: "Prepare style guide",
        startDate: "2025-01-12",
        dueDate: "2025-01-15",
        group: "Design",
        percentCompleted: 0,
        status: "not started",
        division: "UX",
        createdBy: "Lead",
        priority: "Low",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },

  {
    id: 5,
    name: "Arjun Mehta",
    email: "emp5@example.com",
    password: "123",
    taskCount: { active: 1, completed: 1, failed: 0, newTask: 1 },
    tasks: [
      {
        taskId: 501,
        title: "Server Setup",
        description: "Setup staging server",
        startDate: "2025-01-05",
        dueDate: "2025-01-08",
        group: "Backend",
        percentCompleted: 100,
        status: "started",
        division: "Server",
        createdBy: "Admin",
        priority: "High",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskId: 502,
        title: "Logging",
        description: "Implement logging",
        startDate: "2025-01-09",
        dueDate: "2025-01-12",
        group: "Backend",
        percentCompleted: 50,
        status: "started",
        division: "API",
        createdBy: "Lead",
        priority: "Medium",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskId: 503,
        title: "Docs",
        description: "Write API docs",
        startDate: "2025-01-13",
        dueDate: "2025-01-16",
        group: "Backend",
        percentCompleted: 0,
        status: "not started",
        division: "API",
        createdBy: "Admin",
        priority: "Low",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },

  {
    id: 6,
    name: "Priya Nair",
    email: "emp6@example.com",
    password: "123",
    taskCount: { active: 1, completed: 1, failed: 0, newTask: 1 },
    tasks: [
      {
        taskId: 601,
        title: "Test Cases",
        description: "Write test cases",
        startDate: "2025-01-06",
        dueDate: "2025-01-09",
        group: "Testing",
        percentCompleted: 100,
        status: "started",
        division: "QA",
        createdBy: "Lead",
        priority: "High",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskId: 602,
        title: "Bug Verification",
        description: "Verify bug fixes",
        startDate: "2025-01-10",
        dueDate: "2025-01-13",
        group: "Testing",
        percentCompleted: 30,
        status: "started",
        division: "QA",
        createdBy: "Admin",
        priority: "Medium",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskId: 603,
        title: "Automation",
        description: "Setup automation",
        startDate: "2025-01-14",
        dueDate: "2025-01-18",
        group: "Testing",
        percentCompleted: 0,
        status: "not started",
        division: "QA",
        createdBy: "Lead",
        priority: "Low",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },

  {
    id: 7,
    name: "Rahul Singh",
    email: "emp7@example.com",
    password: "123",
    taskCount: { active: 1, completed: 1, failed: 0, newTask: 1 },
    tasks: [
      {
        taskId: 701,
        title: "Requirement Analysis",
        description: "Analyze requirements",
        startDate: "2025-01-07",
        dueDate: "2025-01-10",
        group: "Management",
        percentCompleted: 100,
        status: "started",
        division: "PM",
        createdBy: "Admin",
        priority: "High",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskId: 702,
        title: "Sprint Planning",
        description: "Plan sprint",
        startDate: "2025-01-11",
        dueDate: "2025-01-14",
        group: "Management",
        percentCompleted: 50,
        status: "started",
        division: "PM",
        createdBy: "Lead",
        priority: "Medium",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskId: 703,
        title: "Roadmap",
        description: "Create roadmap",
        startDate: "2025-01-15",
        dueDate: "2025-01-18",
        group: "Management",
        percentCompleted: 0,
        status: "not started",
        division: "PM",
        createdBy: "Admin",
        priority: "Low",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },

  {
    id: 8,
    name: "Neha Kapoor",
    email: "emp8@example.com",
    password: "123",
    taskCount: { active: 1, completed: 1, failed: 0, newTask: 1 },
    tasks: [
      {
        taskId: 801,
        title: "Content Writing",
        description: "Write content",
        startDate: "2025-01-08",
        dueDate: "2025-01-11",
        group: "Marketing",
        percentCompleted: 100,
        status: "started",
        division: "Content",
        createdBy: "Admin",
        priority: "Medium",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskId: 802,
        title: "SEO",
        description: "Optimize SEO",
        startDate: "2025-01-12",
        dueDate: "2025-01-15",
        group: "Marketing",
        percentCompleted: 40,
        status: "started",
        division: "SEO",
        createdBy: "Lead",
        priority: "High",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskId: 803,
        title: "Campaign Plan",
        description: "Plan campaign",
        startDate: "2025-01-16",
        dueDate: "2025-01-19",
        group: "Marketing",
        percentCompleted: 0,
        status: "not started",
        division: "Marketing",
        createdBy: "Admin",
        priority: "Low",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },

  {
    id: 9,
    name: "Vikas Gupta",
    email: "emp9@example.com",
    password: "123",
    taskCount: { active: 1, completed: 1, failed: 0, newTask: 1 },
    tasks: [
      {
        taskId: 901,
        title: "Data Analysis",
        description: "Analyze metrics",
        startDate: "2025-01-09",
        dueDate: "2025-01-12",
        group: "Analytics",
        percentCompleted: 100,
        status: "started",
        division: "Data",
        createdBy: "Lead",
        priority: "High",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskId: 902,
        title: "Report",
        description: "Generate report",
        startDate: "2025-01-13",
        dueDate: "2025-01-16",
        group: "Analytics",
        percentCompleted: 50,
        status: "started",
        division: "Data",
        createdBy: "Admin",
        priority: "Medium",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskId: 903,
        title: "Dashboard",
        description: "Create analytics dashboard",
        startDate: "2025-01-17",
        dueDate: "2025-01-20",
        group: "Analytics",
        percentCompleted: 0,
        status: "not started",
        division: "Data",
        createdBy: "Lead",
        priority: "Low",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },

  {
    id: 10,
    name: "Aditi Rao",
    email: "emp10@example.com",
    password: "123",
    taskCount: { active: 1, completed: 1, failed: 0, newTask: 1 },
    tasks: [
      {
        taskId: 1001,
        title: "HR Policy Review",
        description: "Review HR policies",
        startDate: "2025-01-10",
        dueDate: "2025-01-13",
        group: "HR",
        percentCompleted: 100,
        status: "started",
        division: "HR",
        createdBy: "Admin",
        priority: "High",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskId: 1002,
        title: "Employee Survey",
        description: "Conduct survey",
        startDate: "2025-01-14",
        dueDate: "2025-01-17",
        group: "HR",
        percentCompleted: 50,
        status: "started",
        division: "HR",
        createdBy: "Lead",
        priority: "Medium",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskId: 1003,
        title: "Onboarding Plan",
        description: "Prepare onboarding",
        startDate: "2025-01-18",
        dueDate: "2025-01-21",
        group: "HR",
        percentCompleted: 0,
        status: "not started",
        division: "HR",
        createdBy: "Admin",
        priority: "Low",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
];

const admin = [
  {
    id: 6,
    name: "Lokesh Kumar",
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employee", JSON.stringify(employee));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const empdata = JSON.parse(localStorage.getItem("employee"));
  const admindata = JSON.parse(localStorage.getItem("admin"));

  return { empdata, admindata };
};
